### ISSUE TITLE
key #SkiaCanvas not found in SystemDictionary

### ISSUE THREAD

**Issue by labordep** [pharo-graphics/BlocBenchs#2]
Load the project with: 

```
EpMonitor disableDuring: [
  Author useAuthor: 'Load' during: [
    [	Metacello new
        baseline: 'BlocBenchs';
        repository: 'github://pharo-graphics/BlocBenchs:dev-1.0/src';
        onConflictUseIncoming;
        ignoreImage;
        load.
    ]	on: MCMergeOrLoadWarning
      do: [ :warning | warning load ] ] ]
```

Go to ``BlProfileRunner`` class and start the script ``exampleAll``, ``exampleBoidsFFI``, ``exampleBoidsFPS``,  or ``exampleBoidsFlameGraph``.

![image](https://user-images.githubusercontent.com/49183340/209019971-4e47771e-361b-4e98-9dcb-41a4167218dc.png)

My config :
- Bloc dev-1.0
- Windows 11 Pro
- Pharo-11.0.0+build.389

**Comment by labordep** [comment]
And same thing for `PCMeanConfidenceIntervalPrinter class>>example`

**Comment by tinchodias** [comment]
Thanks. That code compared canvas in the time when Skia was still being loaded in the project.
We should fix it (compare only the remaining canvas)

**Comment by tinchodias** [comment]
Fixed now
